version: 2.1

references:
  #
  # Workspace
  #
  default_container_config: &default_container_config
    docker:
      - image: cimg/node:18.18

  workspace_root: &workspace_root ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  #
  # Caching
  #
  npm_cache_key: &npm_cache_key cache-v002-{{ .Branch }}-{{ checksum "./package-lock.json" }}

  create_npm_cache: &create_npm_cache
    save_cache:
      key: *npm_cache_key
      paths:
        - ./node_modules/

  restore_npm_cache: &restore_npm_cache
    restore_cache:
      keys:
        - *npm_cache_key

  #
  # Filters
  #
  allow_all: &allow_all
    tags:
      only: /.*/
    branches:
      only: /.*/

  only_branch_builds: &only_branch_builds
    tags:
      ignore: /.*/
    branches:
      only: /.*/

  only_tagged_builds: &only_tagged_builds
    tags:
      only: /^v\d+\.\d+\.\d+(?:-\w+\.\d+)?$/
    branches:
      ignore: /.*/

jobs:
  install:
    <<: *default_container_config
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Install dependencies
          command: npm ci
      - *create_npm_cache
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  build:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Run build
          command: make build

  test:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Run verify
          command: make verify -j 3
      - run:
          name: Run tests
          command: make test

  publish:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Set npm credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run:
          name: Bump version number
          command: npm version ${CIRCLE_TAG} --no-git-tag-version
      - run:
          name: Publish to npm registry
          command: npm publish --access=public
          # command: |
          #   export DIST_TAG=$(npx npm-dist-tag)
          #   if [[ $DIST_TAG ]]; then npm publish -- --access=public --tag=${DIST_TAG}; fi

workflows:
  version: 2

  default-workflow:
    jobs:
      - install:
          filters: *allow_all
      - build:
          filters: *allow_all
          requires:
            - install
      - test:
          filters: *allow_all
          requires:
            - install
            - build
      - publish:
          context: npm-publish-token
          filters: *only_tagged_builds
          requires:
            - install
            - build
            - test
